# -*- coding: utf-8 -*-
"""insurancePredict.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YqXeFGaO604Cack387W9Incm97w8S_NU
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
from matplotlib import pyplot as plt
# %matplotlib inline

df=pd.read_csv('insurance.csv')
df.head()

plt.scatter(df.age,df.bought_insurance,color='red',marker='+')

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(df[['age']],df.bought_insurance,test_size=0.10)

from sklearn.linear_model import LogisticRegression

model=LogisticRegression()

model.fit(X_train,y_train)

X_test

y_test

model.predict(X_test)

model.score(X_test,y_test)

model.predict_proba()