# -*- coding: utf-8 -*-
"""saveTesting.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11osrq5RCJaoffc-Zl6cZmWqF4tjVurv6
"""

from turtle import color
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
import joblib

df = pd.read_csv('canada.csv')

df.head()

model = LinearRegression()
model.fit(df[['year']].values,df.income)
model.predict([[2020]])

plt.xlabel('year')
plt.ylabel('per capita income (US$)')
plt.scatter(df.year,df.income,color='red',marker='+')
plt.plot(df.year,model.predict(df[['year']].values),color='blue')
plt.show()

import pickle

with open('model_pickle','wb') as f:
  pickle.dump(model,f )

with open('model_pickle','rb') as f:
  mp=pickle.load(f)

mp.predict([[2020]])

joblib.dump(model,"model_joblib")

